"""
Project Manifest — Milestone 4

Single source of truth for deployment configuration.
All deployment artifact generators (Dockerfile, compose, CI/CD, Railway)
read from this manifest rather than guessing from code.

Generated by the Architect or Synthesizer after code generation,
by analyzing the SkeletonArtifact + generated files.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ServiceType(str, Enum):
    """Type of service the project runs."""
    API = "api"              # FastAPI, Flask, etc.
    CLI = "cli"              # Command-line tool
    WORKER = "worker"        # Background worker/consumer
    CRON = "cron"            # Scheduled task
    STATIC = "static"        # Static site/files


class EnvVar(BaseModel):
    """An environment variable the project needs."""
    name: str
    description: str = ""
    required: bool = True
    default: Optional[str] = None
    secret: bool = False  # If true, never committed to repo

    def env_example_line(self) -> str:
        if self.default:
            return f"{self.name}={self.default}"
        if self.secret:
            return f"{self.name}=your_{self.name.lower()}_here"
        return f"{self.name}="


class ServicePort(BaseModel):
    """A port the service exposes."""
    container_port: int = 8000
    host_port: int = 8000
    protocol: str = "tcp"


class HealthCheck(BaseModel):
    """Health check configuration."""
    path: str = "/health"
    interval_seconds: int = 30
    timeout_seconds: int = 5
    retries: int = 3


class ProjectManifest(BaseModel):
    """
    Complete deployment manifest for a generated project.

    This is the single source of truth that all deployment
    artifact generators read from.
    """
    # Identity
    project_name: str
    description: str = ""
    python_version: str = "3.12"

    # Service
    service_type: ServiceType = ServiceType.API
    entry_command: str = Field(
        default="python -m main",
        description="Command to start the service"
    )
    entry_file: str = "main.py"

    # Network
    ports: list[ServicePort] = Field(default_factory=lambda: [ServicePort()])
    health_check: Optional[HealthCheck] = Field(default_factory=HealthCheck)

    # Dependencies
    pip_packages: list[str] = Field(default_factory=list)
    system_packages: list[str] = Field(default_factory=list)

    # Environment
    env_vars: list[EnvVar] = Field(default_factory=list)

    # Docker
    docker_base_image: str = "python:3.12-slim"
    docker_workdir: str = "/app"
    docker_expose: list[int] = Field(default_factory=lambda: [8000])

    # Volumes (for compose)
    volumes: list[str] = Field(default_factory=list)

    # Additional services (for compose — e.g. postgres, redis)
    depends_on: list[str] = Field(default_factory=list)


def manifest_from_skeleton(
    skeleton,  # SkeletonArtifact
    generated_files: dict[str, str],
) -> ProjectManifest:
    """
    Derive a ProjectManifest from a SkeletonArtifact and generated code.

    Analyzes:
    - External dependencies → pip_packages
    - Entry point → entry_command
    - Config schemas → env_vars
    - Code patterns → service_type, ports
    """
    from belief.models.skeleton import SkeletonArtifact

    # Detect service type from code patterns
    all_code = "\n".join(generated_files.values())
    service_type = ServiceType.CLI
    entry_command = f"python -m {skeleton.entry_point.replace('.py', '').replace('/', '.')}" if skeleton.entry_point else "python -m main"

    if "fastapi" in all_code.lower() or "FastAPI" in all_code:
        service_type = ServiceType.API
        # Find uvicorn pattern or default
        if "uvicorn" in all_code:
            app_module = skeleton.entry_point.replace(".py", "").replace("/", ".") if skeleton.entry_point else "main"
            entry_command = f"uvicorn {app_module}:app --host 0.0.0.0 --port 8000"
        else:
            entry_command = f"python {skeleton.entry_point or 'main.py'}"
    elif "flask" in all_code.lower():
        service_type = ServiceType.API
    elif ".serve_forever" in all_code or ".run()" in all_code:
        service_type = ServiceType.API

    # Extract env vars from config schemas
    env_vars = []
    for config in skeleton.config_schemas:
        prefix = config.env_prefix or ""
        for f in config.fields:
            env_name = f"{prefix}{f.name}".upper()
            env_vars.append(EnvVar(
                name=env_name,
                description=f.description or f"Config: {f.name}",
                required=f.default is None,
                default=f.default.strip('"').strip("'") if f.default and f.default not in ("None", "[]", "{}") else None,
                secret="key" in f.name.lower() or "secret" in f.name.lower() or "token" in f.name.lower() or "password" in f.name.lower(),
            ))

    # Ports
    ports = []
    if service_type == ServiceType.API:
        ports = [ServicePort(container_port=8000, host_port=8000)]

    # Health check
    health = None
    if service_type == ServiceType.API:
        health = HealthCheck(path="/health")

    # Detect additional services
    depends_on = []
    if "postgres" in all_code.lower() or "psycopg" in all_code.lower():
        depends_on.append("postgres")
    if "redis" in all_code.lower():
        depends_on.append("redis")

    return ProjectManifest(
        project_name=skeleton.project_name,
        description=skeleton.description,
        service_type=service_type,
        entry_command=entry_command,
        entry_file=skeleton.entry_point or "main.py",
        ports=ports,
        health_check=health,
        pip_packages=skeleton.external_dependencies,
        env_vars=env_vars,
        docker_expose=[p.container_port for p in ports] if ports else [],
        depends_on=depends_on,
    )
