"""
Deployment Generator — Milestone 4

Generates deployment artifacts from a ProjectManifest:
- Dockerfile (multi-stage, optimized)
- docker-compose.yml (with dependent services)
- .env.example
- GitHub Actions CI/CD workflow
- Railway deployment config (railway.toml)
- requirements.txt

All generators read from the single ProjectManifest —
no code scanning or guessing.
"""

from __future__ import annotations


from belief.models.project_manifest import (
    ProjectManifest,
    ServiceType,
)


# ---------------------------------------------------------------------------
# Dockerfile
# ---------------------------------------------------------------------------

def generate_dockerfile(manifest: ProjectManifest) -> str:
    """Generate an optimized multi-stage Dockerfile."""
    lines = [
        f"# Dockerfile for {manifest.project_name}",
        "# Auto-generated by Belief Engine",
        "",
        f"FROM {manifest.docker_base_image} AS base",
        "",
        "# System dependencies",
        "RUN apt-get update && apt-get install -y --no-install-recommends \\",
        "    gcc \\",
    ]

    for pkg in manifest.system_packages:
        lines.append(f"    {pkg} \\")

    lines.extend([
        "    && rm -rf /var/lib/apt/lists/*",
        "",
        f"WORKDIR {manifest.docker_workdir}",
        "",
        "# Install Python dependencies first (cache layer)",
        "COPY requirements.txt .",
        "RUN pip install --no-cache-dir -r requirements.txt",
        "",
        "# Copy application code",
        "COPY . .",
        "",
    ])

    # Expose ports
    for port in manifest.docker_expose:
        lines.append(f"EXPOSE {port}")

    if manifest.docker_expose:
        lines.append("")

    # Health check
    if manifest.health_check and manifest.service_type == ServiceType.API:
        hc = manifest.health_check
        port = manifest.docker_expose[0] if manifest.docker_expose else 8000
        lines.extend([
            f"HEALTHCHECK --interval={hc.interval_seconds}s --timeout={hc.timeout_seconds}s --retries={hc.retries} \\",
            f'    CMD python -c "import urllib.request; urllib.request.urlopen(\'http://localhost:{port}{hc.path}\')" || exit 1',
            "",
        ])

    # Entry point
    lines.append(f'CMD ["{manifest.entry_command.split()[0]}", '
                 + ", ".join(f'"{arg}"' for arg in manifest.entry_command.split()[1:])
                 + "]")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# docker-compose.yml
# ---------------------------------------------------------------------------

def generate_docker_compose(manifest: ProjectManifest) -> str:
    """Generate docker-compose.yml with dependent services."""
    lines = [
        f"# docker-compose.yml for {manifest.project_name}",
        "# Auto-generated by Belief Engine",
        "",
        "services:",
        f"  {manifest.project_name}:",
        "    build: .",
    ]

    # Ports
    if manifest.ports:
        lines.append("    ports:")
        for port in manifest.ports:
            lines.append(f'      - "{port.host_port}:{port.container_port}"')

    # Environment
    lines.append("    env_file:")
    lines.append("      - .env")

    # Volumes
    if manifest.volumes:
        lines.append("    volumes:")
        for vol in manifest.volumes:
            lines.append(f"      - {vol}")

    # Depends on
    if manifest.depends_on:
        lines.append("    depends_on:")
        for dep in manifest.depends_on:
            lines.append(f"      {dep}:")
            lines.append("        condition: service_healthy")

    # Health check
    if manifest.health_check and manifest.service_type == ServiceType.API:
        hc = manifest.health_check
        port = manifest.ports[0].container_port if manifest.ports else 8000
        lines.extend([
            "    healthcheck:",
            f'      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen(\'http://localhost:{port}{hc.path}\')"]',
            f"      interval: {hc.interval_seconds}s",
            f"      timeout: {hc.timeout_seconds}s",
            f"      retries: {hc.retries}",
        ])

    lines.append("    restart: unless-stopped")

    # Dependent services
    if "postgres" in manifest.depends_on:
        lines.extend([
            "",
            "  postgres:",
            "    image: postgres:16-alpine",
            "    environment:",
            "      POSTGRES_USER: ${POSTGRES_USER:-postgres}",
            "      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}",
            f"      POSTGRES_DB: ${{POSTGRES_DB:-{manifest.project_name}}}",
            "    ports:",
            '      - "5432:5432"',
            "    volumes:",
            "      - pgdata:/var/lib/postgresql/data",
            "    healthcheck:",
            '      test: ["CMD-SHELL", "pg_isready -U postgres"]',
            "      interval: 5s",
            "      timeout: 5s",
            "      retries: 5",
        ])

    if "redis" in manifest.depends_on:
        lines.extend([
            "",
            "  redis:",
            "    image: redis:7-alpine",
            "    ports:",
            '      - "6379:6379"',
            "    healthcheck:",
            '      test: ["CMD", "redis-cli", "ping"]',
            "      interval: 5s",
            "      timeout: 5s",
            "      retries: 5",
        ])

    # Volumes section
    volume_services = [s for s in manifest.depends_on if s in ("postgres",)]
    if volume_services:
        lines.extend([
            "",
            "volumes:",
        ])
        if "postgres" in manifest.depends_on:
            lines.append("  pgdata:")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# .env.example
# ---------------------------------------------------------------------------

def generate_env_example(manifest: ProjectManifest) -> str:
    """Generate .env.example with all required environment variables."""
    lines = [
        f"# Environment variables for {manifest.project_name}",
        "# Copy to .env and fill in values",
        "",
    ]

    # Group: required secrets first
    secrets = [v for v in manifest.env_vars if v.secret]
    required = [v for v in manifest.env_vars if v.required and not v.secret]
    optional = [v for v in manifest.env_vars if not v.required and not v.secret]

    if secrets:
        lines.append("# === Required Secrets ===")
        for v in secrets:
            if v.description:
                lines.append(f"# {v.description}")
            lines.append(v.env_example_line())
        lines.append("")

    if required:
        lines.append("# === Required ===")
        for v in required:
            if v.description:
                lines.append(f"# {v.description}")
            lines.append(v.env_example_line())
        lines.append("")

    if optional:
        lines.append("# === Optional ===")
        for v in optional:
            if v.description:
                lines.append(f"# {v.description}")
            lines.append(v.env_example_line())
        lines.append("")

    # Add dependent service vars
    if "postgres" in manifest.depends_on:
        lines.extend([
            "# === Database ===",
            "POSTGRES_USER=postgres",
            "POSTGRES_PASSWORD=postgres",
            f"POSTGRES_DB={manifest.project_name}",
            f"DATABASE_URL=postgresql://postgres:postgres@postgres:5432/{manifest.project_name}",
            "",
        ])

    if "redis" in manifest.depends_on:
        lines.extend([
            "# === Redis ===",
            "REDIS_URL=redis://redis:6379/0",
            "",
        ])

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# requirements.txt
# ---------------------------------------------------------------------------

def generate_requirements_txt(manifest: ProjectManifest) -> str:
    """Generate requirements.txt from manifest."""
    lines = [f"# Requirements for {manifest.project_name}", ""]
    for pkg in sorted(manifest.pip_packages):
        lines.append(pkg)

    # Add uvicorn if API service
    if manifest.service_type == ServiceType.API and "uvicorn" not in manifest.pip_packages:
        lines.append("uvicorn[standard]")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# GitHub Actions CI/CD
# ---------------------------------------------------------------------------

def generate_github_actions(manifest: ProjectManifest) -> str:
    """Generate .github/workflows/ci.yml."""
    port = manifest.ports[0].container_port if manifest.ports else 8000

    workflow = f"""# CI/CD for {manifest.project_name}
# Auto-generated by Belief Engine

name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "{manifest.python_version}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest tests/ -v

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t {manifest.project_name}:${{{{ github.sha }}}} .

      - name: Test Docker image
        run: |
          docker run -d --name test-container -p {port}:{port} {manifest.project_name}:${{{{ github.sha }}}}
          sleep 5
          curl -f http://localhost:{port}{manifest.health_check.path if manifest.health_check else '/health'} || exit 1
          docker stop test-container
"""
    return workflow


# ---------------------------------------------------------------------------
# Railway config
# ---------------------------------------------------------------------------

def generate_railway_toml(manifest: ProjectManifest) -> str:
    """Generate railway.toml for Railway deployment."""
    port = manifest.ports[0].container_port if manifest.ports else 8000
    hc_path = manifest.health_check.path if manifest.health_check else "/health"

    return f"""# Railway deployment config for {manifest.project_name}
# Auto-generated by Belief Engine

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "{manifest.entry_command}"
healthcheckPath = "{hc_path}"
healthcheckTimeout = {manifest.health_check.timeout_seconds if manifest.health_check else 5}
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "{manifest.project_name}"
internalPort = {port}
"""


# ---------------------------------------------------------------------------
# .dockerignore
# ---------------------------------------------------------------------------

def generate_dockerignore() -> str:
    """Generate .dockerignore."""
    return """# .dockerignore
__pycache__
*.pyc
.git
.gitignore
.env
.env.*
!.env.example
*.md
tests/
.pytest_cache/
.mypy_cache/
.venv/
venv/
"""


# ---------------------------------------------------------------------------
# All artifacts at once
# ---------------------------------------------------------------------------

def generate_all_deployment_artifacts(
    manifest: ProjectManifest,
) -> dict[str, str]:
    """
    Generate all deployment artifacts from a manifest.

    Returns dict of {filename: content}.
    """
    artifacts = {
        "Dockerfile": generate_dockerfile(manifest),
        "docker-compose.yml": generate_docker_compose(manifest),
        ".env.example": generate_env_example(manifest),
        "requirements.txt": generate_requirements_txt(manifest),
        ".dockerignore": generate_dockerignore(),
        ".github/workflows/ci.yml": generate_github_actions(manifest),
        "railway.toml": generate_railway_toml(manifest),
    }

    return artifacts
