"""Architect Agent — Skeleton Architecture (Milestone 1)

Outputs a SkeletonArtifact that captures the full typed interface layer:
- File tree with dependency edges
- Pydantic model chains with all fields typed
- Abstract base classes with method signatures
- Config schemas, exception hierarchies
- Skeleton vs implementation file split

Falls back to old FileManifestPlan if SkeletonArtifact parsing fails.
"""

from __future__ import annotations

import json
import logging
import re

from belief.agents.base import BaseAgent
from belief.config.models import ModelRole
from belief.llm import LLMClient
from belief.models.artifacts import FileManifest, FileManifestPlan
from belief.models.skeleton import (
    SkeletonArtifact,
    FileRole,
)
from belief.models.state import Phase, UnifiedState

logger = logging.getLogger("belief.agents.architect")

_MAX_FILES = {1: 4, 2: 6, 3: 12, 4: 20, 5: 30}

# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

ARCHITECT_SKELETON_SYSTEM = """You are the Architect Agent for an autonomous build system.
Design the complete typed interface layer for a Python project.

Your output is a JSON object matching the SkeletonArtifact schema. This artifact defines
EVERY file in the project, all dependency edges, and all typed interfaces (models, ABCs,
protocols, configs, exceptions) with full signatures.

CRITICAL RULES:
1. Interface before implementation. Define ALL types, ABCs, and protocols before any logic.
2. Every file must have a `role` and `skeleton` flag.
   Models, ABCs, protocols, configs, exceptions → skeleton=true.
   Implementations, entry points → skeleton=false.
3. Dependency edges must form a DAG (no cycles). Models depend on nothing.
   ABCs depend on models. Implementations depend on ABCs + models.
4. Model chains must be in dependency order (base first).
5. All method signatures must have full type annotations.
6. External dependencies must be listed explicitly (pip package names).
7. Keep it practical — generate only the files that are actually needed.
8. For API projects, include an api_contract with all endpoints.
   For CLI projects, include cli_commands in the api_contract.
   The contract is the source of truth for BOTH code generation AND test generation.

SKELETON FILE ROLES (Pass 1 — generated deterministically):
- model: Pydantic models, dataclasses
- abc: Abstract base classes
- config: Settings/config classes
- exception: Custom exception hierarchies

IMPLEMENTATION FILE ROLES (Pass 2 — generated by Builder with LLM):
- impl: Concrete logic implementing ABCs
- entry_point: CLI, main, server entry"""

ARCHITECT_SKELETON_PROMPT = """Design the complete skeleton architecture for this project.

## Goal
{goal}

## Refined Goal
{goal_refined}

## Type: {target_type} | Complexity: {complexity_score}/5 | Max Files: {max_files}
## Strategy: {strategy}

## Plan Steps
{plan_steps}

## Acceptance Criteria
{acceptance_criteria}

## Constraints: {constraints}
## Credentials: {credentials}
## Tools: {tools}
## Research: {recommended_approach}
## Patterns: {patterns}
## Prior Builds: {prior_builds}

Output a complete SkeletonArtifact as JSON. Follow this EXACT schema:

```json
{{
  "project_name": "my_project",
  "description": "What this project does",
  "file_tree": [
    {{"path": "models.py", "role": "model", "description": "Data models", "skeleton": true}},
    {{"path": "base.py", "role": "abc", "description": "Abstract base", "skeleton": true}},
    {{"path": "config.py", "role": "config", "description": "Settings", "skeleton": true}},
    {{"path": "impl.py", "role": "impl", "description": "Implementation", "skeleton": false}},
    {{"path": "main.py", "role": "entry_point", "description": "Entry point", "skeleton": false}}
  ],
  "dependency_edges": [
    {{"source": "base.py", "target": "models.py", "kind": "imports", "symbols": ["RawLead"]}},
    {{"source": "impl.py", "target": "base.py", "kind": "inherits", "symbols": ["PipelineStage"]}}
  ],
  "model_chains": [
    {{
      "name": "Lead",
      "models": [
        {{
          "name": "RawLead",
          "file_path": "models.py",
          "base_class": "BaseModel",
          "fields": [
            {{"name": "source", "type_annotation": "str", "description": "Data source"}},
            {{"name": "website", "type_annotation": "Optional[str]", "default": "None"}}
          ]
        }},
        {{
          "name": "EnrichedLead",
          "file_path": "models.py",
          "base_class": "RawLead",
          "fields": [
            {{"name": "email", "type_annotation": "Optional[str]", "default": "None"}}
          ]
        }}
      ]
    }}
  ],
  "abc_definitions": [
    {{
      "name": "PipelineStage",
      "file_path": "base.py",
      "base_classes": ["ABC"],
      "methods": [
        {{"name": "process", "params": "self, inputs: list[RawLead]", "return_type": "list[EnrichedLead]", "is_abstract": true}}
      ]
    }}
  ],
  "config_schemas": [],
  "exception_specs": [],
  "external_dependencies": ["fastapi", "httpx", "pydantic"],
  "entry_point": "main.py",
  "api_contract": {{
    "endpoints": [
      {{"method": "POST", "path": "/leads", "request_model": "RawLead", "response_model": "EnrichedLead", "status_code": 201, "description": "Create a new lead"}},
      {{"method": "GET", "path": "/leads/{{id}}", "response_model": "EnrichedLead", "status_code": 200, "error_codes": [404], "description": "Get lead by ID"}}
    ],
    "cli_commands": []
  }}
}}
```

CRITICAL FIELD NAMES — use these EXACTLY:
- ModelFieldSpec: "type_annotation" (NOT "type")
- ModelSpec: "file_path" is REQUIRED, "base_class" defaults to "BaseModel"
- ModelChain: "name" (NOT "chain_name")
- ABCDefinition: "name" (NOT "class_name")
- DependencyEdge.kind: must be "imports", "inherits", "implements", or "uses"
- FileTreeEntry.role: must be "model", "abc", "protocol", "config", "exception", "impl", or "entry_point"

Be exhaustive on types and signatures."""


class ArchitectAgent(BaseAgent):
    role = ModelRole.ARCHITECT
    name = "Architect"

    @staticmethod
    def _build_context(state) -> str:
        """Combine TF-IDF similar builds + metabolization nutrient context."""
        parts = []
        if state.similar_builds_context:
            parts.append(state.similar_builds_context)
        if state.nutrient_context:
            parts.append(state.nutrient_context)
        return "\n\n".join(parts) if parts else "No prior builds."

    async def run(self, state: UnifiedState) -> UnifiedState:
        state.phase = Phase.ARCHITECTING
        spec = state.requirement_spec
        plan = state.implementation_plan
        research = state.research_report

        if not spec:
            state.file_manifest = _fallback_manifest(state.user_goal)
            state.phase = Phase.BUILDING
            return state

        max_files = _MAX_FILES.get(state.complexity_score, 12)
        plan_steps = "\n".join(
            f"  {s.order}. {s.description}" for s in (plan.steps[:10] if plan else [])
        ) or "  (no plan available)"

        llm = LLMClient(self.router)
        try:
            prompt = ARCHITECT_SKELETON_PROMPT.format(
                goal=spec.goal,
                goal_refined=spec.goal_refined or spec.goal,
                target_type=spec.target_type,
                complexity_score=state.complexity_score,
                max_files=max_files,
                strategy=plan.strategy if plan else "generate_fresh",
                plan_steps=plan_steps,
                acceptance_criteria="\n".join(f"  - {c}" for c in spec.acceptance_criteria),
                constraints=", ".join(spec.constraints) if spec.constraints else "none",
                credentials=", ".join(c.env_var for c in spec.credentials) if spec.credentials else "none",
                tools=", ".join(spec.tools_needed) if spec.tools_needed else "none",
                recommended_approach=research.recommended_approach if research else "Build from scratch",
                patterns=", ".join(research.patterns_found[:5]) if research and research.patterns_found else "none",
                prior_builds=self._build_context(state),
            )

            # Scale max_tokens with complexity — Tier 4+ projects need more output room
            # for the SkeletonArtifact JSON (20 files × ~200 chars each = ~4K minimum)
            arch_max_tokens = {1: 4096, 2: 6144, 3: 8192, 4: 12288, 5: 16384}.get(
                state.complexity_score, 8192
            )

            raw = await llm.generate_text(
                role=self.role, system=ARCHITECT_SKELETON_SYSTEM, prompt=prompt,
                temperature=0.2, max_tokens=arch_max_tokens, complexity=state.complexity_score,
            )

            skeleton = _parse_skeleton(raw)

            if skeleton and skeleton.file_tree:
                if len(skeleton.file_tree) > max_files:
                    skeleton.file_tree = skeleton.file_tree[:max_files]
                    logger.warning(f"Architect pruned skeleton to {max_files} files")

                state.skeleton_artifact = skeleton
                state.file_manifest = _skeleton_to_manifest(skeleton)

                # ── Phase 2: Detect multi-service projects ──
                # If the skeleton has multiple server/entry files across different
                # packages, or complexity ≥ 5, try to parse as a ServiceArchitecture
                service_arch = _detect_service_architecture(skeleton, state)
                if service_arch:
                    state.code_files["docker-compose.yml"] = service_arch.generate_docker_compose()
                    logger.info(
                        f"Architect: multi-service detected — "
                        f"{len(service_arch.services)} services, "
                        f"docker-compose pre-generated"
                    )

                logger.info(
                    f"Architect: SkeletonArtifact — {len(skeleton.file_tree)} files, "
                    f"{len(skeleton.model_chains)} chains, "
                    f"{len(skeleton.abc_definitions)} ABCs"
                )
            else:
                logger.warning("Architect: skeleton parse failed → fallback")
                state.file_manifest = _fallback_manifest(state.user_goal, spec.target_type)
                state.warnings.append("Architect: skeleton parse failed, used fallback")

        except (ConnectionError, ValueError) as e:
            logger.warning(f"Architect fallback: {e}")
            state.file_manifest = _fallback_manifest(state.user_goal, spec.target_type)
            state.warnings.append(f"Architect fallback: {e}")
        finally:
            await llm.close()

        state.phase = Phase.BUILDING
        return state


def _repair_truncated_json(text: str) -> str | None:
    """Repair truncated JSON from the architect's skeleton output.
    
    Uses the same stack-based approach as belief.llm._repair_json.
    """
    from belief.llm import _repair_json
    return _repair_json(text)


def _parse_skeleton(raw: str) -> SkeletonArtifact | None:
    """Parse SkeletonArtifact from LLM JSON output.
    
    Handles three cases:
    1. Clean JSON — parse directly
    2. Truncated JSON — repair by closing brackets, then parse
    3. Unparseable — return None (fallback to multi-file manifest)
    """
    text = raw.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*\n?", "", text)
        text = re.sub(r"\n?```\s*$", "", text)

    brace_start = text.find("{")
    if brace_start == -1:
        return None

    # Try 1: Find matching closing brace (clean JSON)
    depth = 0
    json_str = None
    for i in range(brace_start, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                json_str = text[brace_start: i + 1]
                break

    if json_str:
        try:
            data = json.loads(json_str)
            return SkeletonArtifact.model_validate(data)
        except Exception as e:
            logger.debug(f"SkeletonArtifact clean parse failed: {e}")

    # Try 2: Repair truncated JSON
    truncated = text[brace_start:]
    repaired = _repair_truncated_json(truncated)
    if repaired:
        try:
            data = json.loads(repaired)
            skeleton = SkeletonArtifact.model_validate(data)
            logger.info(
                f"Architect: repaired truncated JSON — recovered "
                f"{len(skeleton.file_tree)} files"
            )
            return skeleton
        except Exception as e:
            logger.warning(f"SkeletonArtifact repair failed: {e}")

    return None


def _skeleton_to_manifest(skeleton: SkeletonArtifact) -> FileManifestPlan:
    """Convert SkeletonArtifact to FileManifestPlan for backward compat."""
    files = []
    for entry in skeleton.file_tree:
        deps = [e.target for e in skeleton.dependencies_for(entry.path)]
        files.append(FileManifest(
            filename=entry.path,
            purpose=entry.description,
            public_interface="",
            depends_on=deps,
            is_entry_point=(entry.role == FileRole.ENTRY_POINT),
        ))
    return FileManifestPlan(
        files=files,
        architecture_notes=f"Skeleton: {skeleton.description}",
        entry_point=skeleton.entry_point or "main.py",
    )


def _fallback_manifest(goal: str, target_type: str = "python") -> FileManifestPlan:
    """Generate a sensible multi-file manifest when skeleton parsing fails.

    Instead of stuffing everything into main.py (which produces 14K+ char
    monolithic files that truncate and can't be debugged), generate a proper
    multi-file structure based on common patterns.

    The covenant "no file over 200 lines" makes this critical — the fallback
    must produce files small enough for the LLM to generate without truncation.
    """
    goal_lower = goal.lower()

    # Detect what kind of project this is
    has_api = any(kw in goal_lower for kw in ("api", "server", "fastapi", "flask", "endpoint", "rest"))
    has_db = any(kw in goal_lower for kw in ("database", "sqlalchemy", "sql", "sqlite", "postgres", "crud"))
    has_service = any(kw in goal_lower for kw in ("service", "business logic", "service layer"))
    has_tests = any(kw in goal_lower for kw in ("test", "comprehensive"))
    has_pipeline = any(kw in goal_lower for kw in ("pipeline", "stage", "process", "etl", "workflow"))

    files = []

    # Models — always present
    files.append(FileManifest(
        filename="models.py",
        purpose="Data models and schemas",
        public_interface="Pydantic/dataclass models",
        depends_on=[],
    ))

    # Config
    files.append(FileManifest(
        filename="config.py",
        purpose="Configuration and settings",
        public_interface="Settings class",
        depends_on=[],
    ))

    # Exceptions
    files.append(FileManifest(
        filename="exceptions.py",
        purpose="Custom exception classes",
        public_interface="Exception hierarchy",
        depends_on=[],
    ))

    if has_db:
        files.append(FileManifest(
            filename="database.py",
            purpose="Database connection and session management",
            public_interface="get_db(), engine, Base",
            depends_on=["config.py"],
        ))

    if has_service or has_api:
        files.append(FileManifest(
            filename="services.py",
            purpose="Business logic and service layer",
            public_interface="Service classes with CRUD methods",
            depends_on=["models.py", "exceptions.py"] + (["database.py"] if has_db else []),
        ))

    if has_pipeline:
        files.append(FileManifest(
            filename="base.py",
            purpose="Abstract base classes for pipeline stages",
            public_interface="PipelineStage ABC",
            depends_on=["models.py"],
        ))
        files.append(FileManifest(
            filename="stages.py",
            purpose="Pipeline stage implementations",
            public_interface="Stage classes",
            depends_on=["base.py", "models.py"],
        ))
        files.append(FileManifest(
            filename="pipeline.py",
            purpose="Pipeline orchestrator",
            public_interface="Pipeline class, run()",
            depends_on=["stages.py", "models.py"],
        ))

    if has_api:
        files.append(FileManifest(
            filename="routes.py",
            purpose="API route handlers",
            public_interface="FastAPI router with endpoints",
            depends_on=["models.py", "exceptions.py"] + (
                ["services.py"] if has_service else []
            ) + (["database.py"] if has_db else []),
        ))
        files.append(FileManifest(
            filename="server.py",
            purpose="FastAPI application setup and configuration",
            public_interface="app = FastAPI()",
            depends_on=["routes.py", "config.py", "exceptions.py"],
        ))

    # Entry point
    files.append(FileManifest(
        filename="main.py",
        purpose=f"Entry point: {goal[:80]}",
        public_interface="main()",
        is_entry_point=True,
        depends_on=["server.py"] if has_api else (
            ["pipeline.py"] if has_pipeline else ["models.py"]
        ),
    ))

    if has_tests:
        files.append(FileManifest(
            filename="test_main.py",
            purpose="Comprehensive test suite",
            public_interface="pytest test functions",
            depends_on=["models.py"] + (["services.py"] if has_service else []) + (
                ["server.py"] if has_api else []
            ),
        ))

    files.append(FileManifest(filename="requirements.txt", purpose="Dependencies"))

    return FileManifestPlan(
        files=files,
        architecture_notes=f"Fallback manifest — multi-file structure for: {goal[:80]}",
        entry_point="main.py",
    )

# ── Phase 2: Multi-service detection ─────────────────────────────────────────

def _detect_service_architecture(skeleton: SkeletonArtifact, state) -> 'ServiceArchitecture | None':
    """Detect if a skeleton represents a multi-service project.

    Heuristics:
    - Multiple directories with server.py or app.py
    - File tree has 3+ top-level packages (not counting tests/)
    - Goal mentions "microservice", "service", "multi-service"
    - Complexity ≥ 5

    If detected, construct a ServiceArchitecture from the skeleton's file tree.
    """
    try:
        from belief.models.service_architecture import (
            ServiceArchitecture, ServiceSpec, RouteSpec, ServiceDependency,
            SharedModelSpec, CommunicationType,
        )
    except ImportError:
        return None

    # Count distinct packages (top-level directories with .py files)
    packages = set()
    server_files = []
    for entry in skeleton.file_tree:
        parts = entry.path.split("/")
        if len(parts) > 1:
            packages.add(parts[0])
        if entry.path.endswith(("server.py", "app.py", "main.py")) and entry.role.value == "entry_point":
            server_files.append(entry.path)

    # Remove common non-service packages
    packages -= {"tests", "test", "shared", "common", "lib", "utils"}

    goal = state.user_goal.lower() if hasattr(state, 'user_goal') else ""
    is_multi_service = (
        len(server_files) >= 2
        or (len(packages) >= 3 and any(kw in goal for kw in ("microservice", "multi-service", "services")))
        or state.complexity_score >= 5
    )

    if not is_multi_service:
        return None

    # Build ServiceArchitecture from skeleton
    services = []
    shared_models = []

    # Detect shared package
    shared_pkg = None
    for pkg in ["shared", "common", "lib"]:
        if any(e.path.startswith(f"{pkg}/") for e in skeleton.file_tree):
            shared_pkg = pkg
            break

    # Extract shared models from model chains
    if shared_pkg and skeleton.model_chains:
        for chain in skeleton.model_chains:
            for model in chain.models:
                if model.file_path.startswith(f"{shared_pkg}/"):
                    shared_models.append(SharedModelSpec(
                        name=model.name,
                        fields={f.name: f.type_annotation for f in model.fields},
                        description=model.docstring or "",
                    ))

    # Build service specs from packages
    for pkg in sorted(packages):
        pkg_files = [e for e in skeleton.file_tree if e.path.startswith(f"{pkg}/")]
        if not pkg_files:
            continue

        # Detect routes from file tree
        routes = []
        has_server = any(e.path.endswith(("server.py", "app.py")) for e in pkg_files)

        service = ServiceSpec(
            name=pkg.replace("_", "-"),
            package=pkg,
            description=f"Service generated from {pkg}/ package",
            port=8000 + len(services),
            framework="fastapi",
            files=[e.path.split("/", 1)[1] for e in pkg_files if not e.path.endswith("__init__.py")],
            routes=routes,
        )
        services.append(service)

    if len(services) < 2:
        return None

    arch = ServiceArchitecture(
        system_name=skeleton.project_name,
        description=skeleton.description,
        services=services,
        shared_models=shared_models,
        shared_package=shared_pkg or "shared",
    )

    logger.info(
        f"Architect: detected ServiceArchitecture — "
        f"{len(services)} services, {len(shared_models)} shared models"
    )

    return arch
